# Generated by Django 5.1.1 on 2025-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_remove_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='default', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
