# Generated by Django 5.1.1 on 2025-07-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
    ]
